[theme]
	name = "gruvbox-dark"
[theme.overrides]
	separator = ""

[icons]
	name = "none"

#[[block]]
#	block = "music"
#	buttons = ["play", "next"]

[[block]]
	block = "focused_window"
	max_width = 20
	show_marks = "visible"

[[block]]
	block = "net"
	format = ""

[[block]]
	block = "disk_space"
	path = "/"
	alias = "/"
	info_type = "available"
	unit = "GB"
	interval = 20
	warning = 20.0
	alert = 10.0

[[block]]
	block = "memory"
	display_type = "memory"
	format_mem = "{mem_used}/{mem_total}({mem_used_percents})"
	format_swap = "{swap_used}/{swap_total}({swap_used_percents})"

[[block]]
	block = "cpu"
	interval = 1

[[block]]
	block = "load"
	interval = 1
	format = "{1m}"

[[block]]
	block = "sound"

[[block]]
	block = "temperature"
	collapsed = false
	driver = "sysfs"
	chip = "coretemp"
	format = "{average}"

[[block]]
	block = "battery"
	device = "BAT1"
	interval = 10
	format = "{percentage} {power} {time}"
	full_format = "{power} "

#[[block]]
#	block = "keyboard_layout"
#	driver = "sway"

[[block]]
	block = "time"
	interval = 60
	format = "%e %b %y %R"
